# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='No Desc'),
            preserve_default=False,
        ),
    ]
